/**
 * Library-owned DDL for the `fusion` database — the tables `scripts/pg-import/ddl.sql`
 * (ddl_version 1, agent B's landed artifact) does NOT create, all of them customer-owned
 * operational state that no vendor dump carries:
 *
 *   customer.enrich          the staging queue's durable copy (ddl_version 1 has `enrich` only in
 *                            the VERSION schema, holding the vendor's already-enriched rows; the
 *                            dual-write keeps the customer's staged rows across an upgrade)
 *   customer.enrich_usage    LLM cost ledger
 *   customer.batch_jobs/_items, gjob_jobs/_items/_control   enrichment job control
 *
 * Forward-only and versioned in `meta.library_migrations`, applied under a transaction advisory
 * lock (engine idiom, `gnimsys-agent-core/src/db/migrations.ts`). The vendor schema is NEVER
 * touched here — its shape belongs to ddl.sql and the upgrade job.
 */

/** Same column list as `{{V}}.enrich` in scripts/pg-import/ddl.sql (one shape, two schemas). */
const ENRICH = (s: string) => `
CREATE TABLE IF NOT EXISTS ${s}.enrich (
  id                 text PRIMARY KEY,
  source             text,
  title              text,
  source_hash        text,
  original_sql       text,
  clean_sql          text,
  description        text,
  tables_used        text,
  lookup_types       text,
  joins              text,
  filters            text,
  security_predicate text,
  approved           integer DEFAULT 0,
  reports            text,
  intents            text,
  mechanics          text
);`;

const JOBS = (s: string) => `
CREATE TABLE IF NOT EXISTS ${s}.enrich_usage (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts                    text NOT NULL,
  model                 text NOT NULL,
  source                text,
  n_items               integer NOT NULL DEFAULT 0,
  input_tokens          bigint NOT NULL DEFAULT 0,
  output_tokens         bigint NOT NULL DEFAULT 0,
  cache_read_tokens     bigint NOT NULL DEFAULT 0,
  cache_creation_tokens bigint NOT NULL DEFAULT 0,
  sql_chars             bigint,
  batch_id              text
);
CREATE INDEX IF NOT EXISTS ix_enrich_usage_batch ON ${s}.enrich_usage (batch_id);
CREATE TABLE IF NOT EXISTS ${s}.batch_jobs (
  batch_id     text PRIMARY KEY,
  model        text NOT NULL,
  n            integer NOT NULL,
  submitted_at text NOT NULL,
  status       text NOT NULL,
  completed_at text,
  note         text
);
CREATE TABLE IF NOT EXISTS ${s}.batch_items (
  batch_id  text NOT NULL,
  custom_id text NOT NULL,
  row_id    text NOT NULL,
  PRIMARY KEY (batch_id, custom_id)
);
CREATE INDEX IF NOT EXISTS ix_batch_items_row ON ${s}.batch_items (row_id);
CREATE TABLE IF NOT EXISTS ${s}.gjob_jobs (
  name         text PRIMARY KEY,
  model        text NOT NULL,
  n            integer NOT NULL,
  submitted_at text,
  status       text,
  note         text
);
CREATE TABLE IF NOT EXISTS ${s}.gjob_items (
  name   text NOT NULL,
  idx    integer NOT NULL,
  row_id text NOT NULL,
  PRIMARY KEY (name, idx)
);
CREATE INDEX IF NOT EXISTS ix_gjob_items_row ON ${s}.gjob_items (row_id);
CREATE TABLE IF NOT EXISTS ${s}.gjob_control (
  id         integer PRIMARY KEY CHECK (id = 1),
  active     integer NOT NULL DEFAULT 0,
  sources    text,
  model      text,
  cap        integer,
  wave       integer,
  batch_size integer
);`;

export const LIBRARY_MIGRATIONS: ReadonlyArray<{ version: number; sql: (customer: string) => string }> = [
  { version: 1, sql: (c) => `${ENRICH(c)}\n${JOBS(c)}` },
];
