-- fusion database DDL (spec 2026-09-16 D13, plan decisions 2026-09-18): schema-per-version catalog.
-- ddl_version: 1
--
-- Blocks (applied by import.mts, in this order):
--   @block meta    — schema `meta`: seeds + the single-row active_version pointer
--   @block corpus  — {{S}} = the corpus/registry DDL shared by every version schema AND `customer`
--   @block vendor  — {{V}} = vendor-only data of one delivered version (schema catalog, registries,
--                    layout corpus, enrich store, col_vec)
-- {{S}} / {{V}} are replaced by the importer with the target schema name (e.g. v2026_09). Every
-- statement is idempotent (IF NOT EXISTS) so `customer` survives repeated imports untouched.
--
-- Types: SQLite 384×float32 BLOB → vector(384); JSON-in-text stays text (readers JSON.parse it; jsonb
-- would change the client wire shape — a port-time decision). Registries live ONLY in the version
-- schema (computed over vendor ∪ customer at upgrade time); `customer` = corpus + flex/adf + rules.
-- Vector indexes: NONE yet — exact scan (`ORDER BY embedding <-> $1`) is the baseline at ~100k rows.
-- When an ANN index is wanted it goes right after the two corpus vector tables (same L2 metric as
-- sqlite-vec's default), either pgvector's HNSW or vectorscale's DiskANN (`vectorscale` is installed):
--   CREATE INDEX ... ON {{S}}.report_queries           USING hnsw    (embedding vector_l2_ops);
--   CREATE INDEX ... ON {{S}}.report_queries_vec_multi USING hnsw    (embedding vector_l2_ops);
--   CREATE INDEX ... ON {{S}}.report_queries           USING diskann (embedding vector_l2_ops);
--   CREATE INDEX ... ON {{S}}.report_queries_vec_multi USING diskann (embedding vector_l2_ops);

-- @block meta
CREATE EXTENSION IF NOT EXISTS vector;
CREATE SCHEMA IF NOT EXISTS meta;

CREATE TABLE IF NOT EXISTS meta.seeds (
  version         text PRIMARY KEY,            -- = the schema name, e.g. v2026_09
  embedding_model text NOT NULL,               -- from the seed's catalog_meta.embedding_version
  ddl_version     text NOT NULL,               -- the "ddl_version:" header of this file
  restored_at     timestamptz NOT NULL DEFAULT now(),
  activated_at    timestamptz
);

-- single-row pointer: which version schema serves reads (search_path = <version>, meta)
CREATE TABLE IF NOT EXISTS meta.active_version (
  lock        boolean PRIMARY KEY DEFAULT true CHECK (lock),
  version     text NOT NULL REFERENCES meta.seeds(version),
  switched_at timestamptz NOT NULL DEFAULT now()
);

-- @block corpus
CREATE SCHEMA IF NOT EXISTS {{S}};

-- the SQL corpus (was reports.sqlite report_queries + report_queries_vec: the vec0 shadow table is
-- folded into the `embedding` column — pgvector searches the column directly)
CREATE TABLE IF NOT EXISTS {{S}}.report_queries (
  rid                bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,  -- was SQLite rowid (vec_multi join key)
  id                 text PRIMARY KEY,
  source             text,
  title              text,
  original_sql       text,
  clean_sql          text,
  description        text,
  tables_used        text,          -- JSON array (text)
  joins              text,          -- JSON (text)
  filters            text,          -- JSON (text)
  lookup_types       text,          -- JSON (text)
  security_predicate text,
  approved           integer,
  reports            text,          -- JSON (text)
  embedding          vector(384),
  intents            text,          -- JSON array (text)
  mechanics          text,
  semantics_json     text,
  low_confidence     integer,
  origin             text NOT NULL DEFAULT 'vendor' CHECK (origin IN ('vendor','customer'))
);
CREATE INDEX IF NOT EXISTS ix_rq_source ON {{S}}.report_queries (source);
-- title = ? and title LIKE ? (getReportQuery byTitle/siblings/byArea/near)
CREATE INDEX IF NOT EXISTS ix_rq_title  ON {{S}}.report_queries (title text_pattern_ops);
-- id LIKE ? (ingestStore prefix deletes)
CREATE INDEX IF NOT EXISTS ix_rq_id_pat ON {{S}}.report_queries (id text_pattern_ops);

-- multi-vector KNN rows: one per intent phrasing, joined back by qrowid (= report_queries.rid)
CREATE TABLE IF NOT EXISTS {{S}}.report_queries_vec_multi (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- was vec0 rowid
  qrowid    bigint NOT NULL REFERENCES {{S}}.report_queries(rid) ON DELETE CASCADE,
  embedding vector(384) NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_rq_multi_qrowid ON {{S}}.report_queries_vec_multi (qrowid);

-- flexfield registry (DFF/EFF segments → physical columns)
CREATE TABLE IF NOT EXISTS {{S}}.flexfields (
  application_id    integer,
  flexfield_type    text NOT NULL,
  flexfield_code    text NOT NULL,
  deployment_status text,
  context_code      text NOT NULL,
  context_enabled   text,
  multirow          text,
  translatable      text,
  segment_code      text NOT NULL,
  column_name       text,
  sequence_number   integer,
  segment_name      text,
  prompt            text,
  display_type      text,
  value_set_id      integer,
  required          text,
  segment_enabled   text,
  source            text NOT NULL,
  loaded_at         text NOT NULL,
  UNIQUE (flexfield_type, application_id, flexfield_code, context_code, segment_code, source)
);
CREATE INDEX IF NOT EXISTS idx_flex_code    ON {{S}}.flexfields (flexfield_code);
CREATE INDEX IF NOT EXISTS idx_flex_context ON {{S}}.flexfields (context_code);
CREATE INDEX IF NOT EXISTS idx_flex_column  ON {{S}}.flexfields (column_name);

-- ADF custom objects / custom fields → EXTN_ATTRIBUTE_* columns
CREATE TABLE IF NOT EXISTS {{S}}.adf_extensions (
  object_name         text,
  table_name          text NOT NULL,
  context_column_name text,
  attribute_name      text NOT NULL,
  column_name         text NOT NULL,
  source              text NOT NULL,
  loaded_at           text NOT NULL,
  display_hint        text,
  object_display      text,
  field_display       text,
  UNIQUE (object_name, table_name, attribute_name, column_name, source)
);
CREATE INDEX IF NOT EXISTS idx_adf_object ON {{S}}.adf_extensions (object_name);
CREATE INDEX IF NOT EXISTS idx_adf_table  ON {{S}}.adf_extensions (table_name);
CREATE INDEX IF NOT EXISTS idx_adf_attr   ON {{S}}.adf_extensions (attribute_name);

-- human/agent-authored table facts (was facts.sqlite table_rules)
CREATE TABLE IF NOT EXISTS {{S}}.table_rules (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name  text NOT NULL,
  scope       text NOT NULL DEFAULT 'table',
  column_name text,
  kind        text NOT NULL,
  grain       text,
  dedup       text,
  body        text,
  author      text,
  source      text NOT NULL DEFAULT 'human',
  enabled     integer NOT NULL DEFAULT 1,
  updated_at  text
);
CREATE INDEX IF NOT EXISTS ix_table_rules ON {{S}}.table_rules (table_name, enabled);
CREATE TABLE IF NOT EXISTS {{S}}.facts_meta (k text PRIMARY KEY, v text);

-- @block vendor
CREATE SCHEMA IF NOT EXISTS {{V}};

-- was schema.sqlite `meta` (schema/queries version, counts, embedding_version, built_at_epoch)
CREATE TABLE IF NOT EXISTS {{V}}.catalog_meta (key text PRIMARY KEY, value text);

-- Oracle Fusion schema catalog (schema.sqlite). `search` replaces FTS5 tables_fts(name, remarks, module):
-- weights A/B/C keep name > module > remarks for ts_rank; the 'simple' config lowercases and splits
-- on '_' exactly like FTS5 unicode61, so `tok:*` prefix queries port 1:1.
CREATE TABLE IF NOT EXISTS {{V}}.tables (
  name      text PRIMARY KEY,
  schema    text,
  type      text,
  module    text,
  remarks   text,
  view_text text,
  search    tsvector GENERATED ALWAYS AS (
              setweight(to_tsvector('simple', coalesce(name, '')),    'A') ||
              setweight(to_tsvector('simple', coalesce(module, '')),  'B') ||
              setweight(to_tsvector('simple', coalesce(remarks, '')), 'C')) STORED
);
CREATE INDEX IF NOT EXISTS ix_tables_search ON {{V}}.tables USING gin (search);

CREATE TABLE IF NOT EXISTS {{V}}.columns (
  table_name text NOT NULL,
  name       text NOT NULL,
  data_type  text,
  size       integer,
  nullable   integer,
  remarks    text,
  ordinal    integer
);
CREATE INDEX IF NOT EXISTS idx_columns_table ON {{V}}.columns (table_name);
CREATE INDEX IF NOT EXISTS idx_columns_name  ON {{V}}.columns (name);

CREATE TABLE IF NOT EXISTS {{V}}.pkeys (
  table_name  text NOT NULL,
  column_name text NOT NULL,
  seq         integer
);
CREATE INDEX IF NOT EXISTS idx_pkeys_table ON {{V}}.pkeys (table_name);

CREATE TABLE IF NOT EXISTS {{V}}.fkeys (
  child_table  text NOT NULL,
  parent_table text NOT NULL,
  column_name  text,
  seq          integer,
  name         text
);
CREATE INDEX IF NOT EXISTS idx_fkeys_child  ON {{V}}.fkeys (child_table);
CREATE INDEX IF NOT EXISTS idx_fkeys_parent ON {{V}}.fkeys (parent_table);

CREATE TABLE IF NOT EXISTS {{V}}.indexes (
  table_name  text NOT NULL,
  index_name  text NOT NULL,
  is_unique   integer,
  ordinal     integer,
  column_name text
);
CREATE INDEX IF NOT EXISTS idx_indexes_table ON {{V}}.indexes (table_name);

CREATE TABLE IF NOT EXISTS {{V}}.relationships (
  from_table  text NOT NULL,
  from_col    text,
  to_table    text NOT NULL,
  to_col      text,
  evidence    text,
  occurrences integer,
  confidence  text,
  predicate   text,
  source      text
);
CREATE INDEX IF NOT EXISTS idx_rel_from ON {{V}}.relationships (from_table);
CREATE INDEX IF NOT EXISTS idx_rel_to   ON {{V}}.relationships (to_table);

-- registries (boot-built over the corpus today; computed over vendor ∪ customer at upgrade time)
CREATE TABLE IF NOT EXISTS {{V}}.table_usages (
  table_name text NOT NULL,
  query_id   text NOT NULL,
  source     text,
  title      text,
  sql_chars  integer NOT NULL DEFAULT 0,
  score      integer NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS ix_table_usages ON {{V}}.table_usages (table_name, score DESC);
CREATE TABLE IF NOT EXISTS {{V}}.usage_meta (k text PRIMARY KEY, v text);

CREATE TABLE IF NOT EXISTS {{V}}.table_predicates (
  table_name  text NOT NULL,
  column_name text NOT NULL,
  op          text NOT NULL,
  literal     text NOT NULL,
  occurrences integer NOT NULL DEFAULT 0,
  role        text NOT NULL DEFAULT 'structural'
);
CREATE INDEX IF NOT EXISTS ix_table_predicates ON {{V}}.table_predicates (table_name);
CREATE TABLE IF NOT EXISTS {{V}}.pred_meta (k text PRIMARY KEY, v text);

CREATE TABLE IF NOT EXISTS {{V}}.table_join_columns (
  table_name  text NOT NULL,
  column_name text NOT NULL,
  units       integer NOT NULL,
  share       double precision NOT NULL,
  PRIMARY KEY (table_name, column_name)
);

CREATE TABLE IF NOT EXISTS {{V}}.table_grain (
  table_name      text PRIMARY KEY,
  grain           text NOT NULL,
  multi_row       integer NOT NULL,
  dedup           text,
  signals         text,            -- JSON array (text)
  corpus_evidence integer NOT NULL DEFAULT 0,
  note            text,
  updated_at      text
);
CREATE TABLE IF NOT EXISTS {{V}}.grain_meta (k text PRIMARY KEY, v text);

-- curated layout-pattern corpus + its intent vectors (was layout_patterns / layout_patterns_vec)
CREATE TABLE IF NOT EXISTS {{V}}.layout_patterns (
  rid              bigint PRIMARY KEY,           -- was SQLite rowid (layout_patterns_vec.prowid)
  id               text UNIQUE NOT NULL,
  kind             text NOT NULL,
  name             text NOT NULL,
  format           text NOT NULL,
  format_exclusive integer DEFAULT 0,
  dsl_support      text NOT NULL,
  description      text NOT NULL,
  when_to_use      text NOT NULL,
  intents          text NOT NULL,   -- JSON (text)
  requires         text,            -- JSON (text)
  composition      text,            -- JSON (text)
  recipe           text,            -- JSON (text)
  fixture_ref      text,
  pitfalls         text,            -- JSON (text)
  trigger          text,
  why              text,
  instead          text,            -- JSON (text)
  alternative      text,
  source_refs      text,
  verified         text NOT NULL,
  dsl_version      text,
  verified_at      text
);
CREATE TABLE IF NOT EXISTS {{V}}.layout_patterns_vec (
  id        bigint PRIMARY KEY,                  -- was vec0 rowid
  prowid    bigint NOT NULL REFERENCES {{V}}.layout_patterns(rid) ON DELETE CASCADE,
  embedding vector(384) NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_layout_vec_prowid ON {{V}}.layout_patterns_vec (prowid);
CREATE TABLE IF NOT EXISTS {{V}}.layout_meta (k text PRIMARY KEY, v text);

-- enrich store (was enrich.sqlite): LLM enrichment per corpus unit
CREATE TABLE IF NOT EXISTS {{V}}.enrich (
  id                 text PRIMARY KEY,
  source             text,
  title              text,
  source_hash        text,
  original_sql       text,
  clean_sql          text,
  description        text,
  tables_used        text,          -- JSON (text)
  lookup_types       text,          -- JSON (text)
  joins              text,          -- JSON (text)
  filters            text,          -- JSON (text)
  security_predicate text,
  approved           integer DEFAULT 0,
  reports            text,          -- JSON (text)
  intents            text,          -- JSON (text)
  mechanics          text
);

-- column-text embedding cache (was colcache.sqlite col_vec: hash → 384×float32)
CREATE TABLE IF NOT EXISTS {{V}}.col_vec (
  hash text PRIMARY KEY,
  vec  vector(384) NOT NULL
);
